import { GoogleGenAI } from '@google/genai';
import * as FileSystem from 'expo-file-system/legacy';

const API_KEY = process.env.EXPO_PUBLIC_GEMINI_API_KEY;

const genAI = new GoogleGenAI({ apiKey: API_KEY || '' });
const GEMINI_MODEL = 'gemini-2.5-flash-lite';

export interface QuizQuestion {
    question: string;
    options: string[];
    answer: number;
}

export interface StudyMaterial {
    explanation: string;
    summary: string[];
    quiz: QuizQuestion[];
}

export interface RevisionSheet {
    title: string;
    description: string;
    definitions: { term: string; definition: string; flashcardQuestion?: string }[];
    keyPoints: string[];
    faq: { question: string; answer: string }[];
}

export const generateStudyMaterial = async (imageUri: string, base64Data?: string): Promise<StudyMaterial> => {
    console.log("AI SERVICE: generateStudyMaterial called");
    console.log("AI SERVICE: uri:", imageUri ? "YES" : "NO");
    console.log("AI SERVICE: has base64Data:", !!base64Data);

    if (!API_KEY) {
        console.warn("Gemini API Key is missing");
        return MOCK_RESULT;
    }

    try {
        let base64 = base64Data;
        
        if (!base64) {
            console.log("AI SERVICE: Falling back to FileSystem.readAsStringAsync");
            base64 = await FileSystem.readAsStringAsync(imageUri, {
                encoding: 'base64',
            });
        }

        const prompt = `
            Analyze this image of study notes, textbooks, or handwriting. 
            Extract and organize the core educational content into a structured JSON format.
            
            Return exactly this structure:
            {
                "explanation": "A comprehensive yet easy-to-understand explanation of the key concepts identified in the image (2-4 paragraphs). Use markdown for bolding terms.",
                "summary": [
                    "Key point 1",
                    "Key point 2",
                    "Key point 3"
                ],
                "quiz": [
                    {
                        "question": "A multiple choice question based on the content.",
                        "options": ["Option A", "Option B", "Option C", "Option D"],
                        "answer": 0 
                    }
                ]
            }
            
            Rules:
            - The "answer" must be the index (0-3) of the correct option in the "options" array.
            - Provide up to 20 quiz questions.
            - Provide 5-15 summary points.
            - If handwriting is illegible, make an educated guess or focus on legible parts.
        `;

        const result = await genAI.models.generateContent({
            model: "gemini-2.5-flash-lite",
            contents: [
                {
                    role: 'user',
                    parts: [
                        { text: prompt },
                        {
                            inlineData: {
                                data: base64,
                                mimeType: "image/jpeg"
                            }
                        }
                    ]
                }
            ],
            config: {
                responseMimeType: "application/json",
            }
        });

        const candidate = result.candidates?.[0];
        const text = candidate?.content?.parts?.[0]?.text;

        if (!text) {
            console.error('Gemini API empty response:', result);
            throw new Error('No content was generated by the Gemini model.');
        }

        let jsonStr = text;
        const jsonStart = text.indexOf('{');
        const jsonEnd = text.lastIndexOf('}');

        if (jsonStart !== -1 && jsonEnd !== -1) {
            jsonStr = text.substring(jsonStart, jsonEnd + 1);
        }

        const parsed: StudyMaterial = JSON.parse(jsonStr);

        if (!parsed.explanation || !Array.isArray(parsed.summary) || !Array.isArray(parsed.quiz)) {
            throw new Error('Invalid JSON structure returned by Gemini');
        }

        return parsed;

    } catch (error) {
        console.error('Gemini API Error:', error);
        throw error;
    }
};

const MOCK_RESULT: StudyMaterial = {
    explanation: "Photosynthesis is the process used by plants, algae and certain bacteria to harness energy from sunlight and turn it into chemical energy.",
    summary: [
        "Converts light energy to chemical energy.",
        "Occurs in chloroplasts.",
        "Produces glucose and oxygen."
    ],
    quiz: [
        {
            question: "Where does photosynthesis occur?",
            options: ["Mitochondria", "Chloroplasts", "Nucleus", "Ribosomes"],
            answer: 1
        },
        {
            question: "What is the primary output of photosynthesis?",
            options: ["Carbon Dioxide", "Water", "Glucose", "Nitrogen"],
            answer: 2
        },
        {
            question: "Which pigment absorbs light energy?",
            options: ["Hemoglobin", "Chlorophyll", "Melanin", "Carotene"],
            answer: 1
        }
    ]
};

export const sendChatMessage = async (
    history: { role: string; text: string }[], 
    newMessage: string,
    sheetContext?: any
) => {
    if (!API_KEY) {
        return "Thinking... (Mock Response: I see you're asking about this topic. Have you checked the Key Definitions section yet?)";
    }

    try {
        const contents = history.map(h => ({
            role: h.role === 'ai' || h.role === 'assistant' || h.role === 'model' ? 'model' : 'user',
            parts: [{ text: h.text }]
        }));

        contents.push({
            role: 'user',
            parts: [{ text: newMessage }]
        });
        
        // Build robust system instruction with Sheet Context
        let systemInstruction = `You are an expert AI tutor explaining study material. Be super helpful, concise, and encourage learning.

CRITICAL MATH/LATEX RULES:
- Use standard Markdown for text: **bold**, *italic*, bullet lists.
- For ALL math, MUST wrap in dollar signs: inline $expression$ or block $$expression$$.
- NEVER write raw LaTeX commands outside dollar signs.
- NEVER invent LaTeX commands for units (like \\Js, \\J, \\m). Use regular text for units: $10 \\text{ J\\cdot s}$ or just $10$ J s.
- Keep equations SHORT. Break long formulas into multiple $$ blocks, one step per line.
- Use simple LaTeX only. Subscripts: $CO_{2}$. Fractions: \\frac{a}{b}.
- For infinitesimal/differentials: Use $d x$ or $d t$ instead of \\dx or \\dt.
- For ALL arrows: Use \\rightarrow or \\to.
- For equilibrium: Use \\rightleftharpoons.
- ALWAYS use \\text{} for units: $10 \\text{ J}$.
- For chemical reactions: $6CO_{2} + 6H_{2}O \\rightarrow C_{6}H_{12}O_{6} + 6O_{2}$
- For step-by-step: use **Step 1:**, **Step 2:** labels with each math step on its own $$ block.`;

        if (sheetContext) {
            systemInstruction += `\n\nCONTEXT OF THE REVISION SHEET THE STUDENT IS STUDYING:\n`;
            if (sheetContext.title) systemInstruction += `Title: ${sheetContext.title}\n`;
            if (sheetContext.description) systemInstruction += `Description: ${sheetContext.description}\n`;
            if (sheetContext.keyPoints && sheetContext.keyPoints.length) {
                systemInstruction += `Key Points:\n${sheetContext.keyPoints.map((p: string) => '- ' + p).join('\n')}\n`;
            }
            systemInstruction += `Use this context to accurately answer doubts relating to this topic.`;
        }

        const result = await genAI.models.generateContent({
            model: GEMINI_MODEL,
            contents: contents,
            config: {
                systemInstruction: systemInstruction,
            }
        });

        const text = result.candidates?.[0]?.content?.parts?.[0]?.text;
        
        if (!text) throw new Error("No response from AI");
        return text;
    } catch (error) {
        console.error("Gemini Chat Error:", error);
        throw error;
    }
};

export const generateRevisionSheet = async (topic: string, subject?: string, detailLevel: string = 'Normal'): Promise<RevisionSheet> => {
    if (!API_KEY) {
        throw new Error("Gemini API Key is missing");
    }

    try {
        const prompt = `
            Create a highly detailed, comprehensive, and academically rigorous revision sheet for the topic: "${topic}"${subject ? ` in the subject of ${subject}` : ''}.
            The detail level should be: ${detailLevel}. (If 'Normal', make it high school/college level. If 'Detailed', make it extremely comprehensive).

            CRITICAL REQUIREMENT: Do not provide surface-level "showcase" content. Provide REAL, deep educational content.
            - If this is a Math/Physics/Science topic, you MUST include important formulas, equations, and mathematical laws in your definitions and key points!
            - If it's a theoretical topic, provide real historical dates, specific examples, and deep conceptual explanations.
            - The content must instantly help a student pass a real exam on this exact topic.

            MATH/LATEX FORMATTING RULES (MUST follow exactly):
            - For ALL math expressions, wrap them in dollar signs: inline $expression$ or block $$expression$$.
            - CRITICAL: NEVER use a backslash "\\" for LaTeX commands. It breaks our JSON parser.
            - INSTEAD, use double at-sign "@@" for ALL LaTeX commands.
            - Example: use "@@frac{a}{b}" instead of "\\frac{a}{b}". 
            - Example: use "@@rightarrow" instead of "\\rightarrow".
            - Example: "@@lambda", "@@sqrt{2}", "@@Delta", "@@sum".
            - PUT UNITS OUTSIDE MATH BLOCKS! Example: $10$ J s, not $10 @@text{J s}$ or $10 @@Js$.
            - For chemical equations: $6CO_{2} + 6H_{2}O @@rightarrow C_{6}H_{12}O_{6} + 6O_{2}$
            - PREFERRED SCIENCE LATEX:
                - Differentials: Use "d x", "d t" (NOT @@dx, @@dt).
                - Equilibrium: Use "@@rightleftharpoons".
                - Standard Arrows: Use "@@rightarrow" or "@@to".
                - Partial derivatives: Use "@@partial".
                - Greek: @@alpha, @@beta, @@gamma, @@Delta, @@lambda, @@omega, @@mu, @@pi.
            - NEVER use these banned commands: @@dx, @@dt, @@dv, @@du, @@\, @@multicolumn, @@hline, @@cline, @@begin{tabular}, @@end{tabular}, @@newline, @@arraystretch, @@toprule, @@midrule, @@bottomrule, @@begin{array}, @@abs, @@norm, @@ket, @@bra, @@lVert, @@rVert, @@lvert, @@rvert.
            - Keep formulas SHORT. Never write extremely long single-line equations.
            - Ensure all strings are valid JSON. Keep newlines as \\n.

            Organize the content into exactly this structure:
            {
                "title": "A clear, concise title indicating the specific topic",
                "description": "A deep, engaging introduction and explanation of the topic (1-2 paragraphs). Focus on real meaning and application. Wrap any math in $ delimiters.",
                "definitions": [
                    { 
                        "term": "Key Term or Formula Name", 
                        "definition": "Highly detailed definition, including the actual formula wrapped in $ delimiters if applicable",
                        "flashcardQuestion": "A thought-provoking question to test the user's knowledge of this term"
                    }
                ],
                "keyPoints": [
                    "Detailed fundamental concept with concise explanation. Wrap any formulas in $ delimiters."
                ],
                "faq": [
                    { "question": "Deep conceptual question?", "answer": "Clear concise detailed answer with math in $ delimiters if needed" }
                ]
            }
            
            Rules:
            - Use professional and educational language.
            - Provide 4-6 definitions.
            - Provide 4-6 key points.
            - Provide 3-5 FAQs.
            - Always return valid JSON.
            - ALL math MUST be inside $ or $$ delimiters. No raw LaTeX outside delimiters.
        `;

        const result = await genAI.models.generateContent({
            model: "gemini-2.5-flash-lite",
            contents: [{ role: 'user', parts: [{ text: prompt }] }],
            config: {
                responseMimeType: "application/json",
            }
        });

        const text = result.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!text) throw new Error('No content was generated by Gemini');

        let jsonStr = text;
        const jsonStart = text.indexOf('{');
        const jsonEnd = text.lastIndexOf('}');
        if (jsonStart !== -1 && jsonEnd !== -1) {
            jsonStr = text.substring(jsonStart, jsonEnd + 1);
        }

        // Replace the @@ placeholder back to backslash for LaTeX
        let sanitizedJson = jsonStr.replace(/@@/g, '\\');
        
        // BULLETPROOF: Fix ALL invalid JSON escape sequences.
        // In JSON, only these are valid after a backslash: " \ / b f n r t u
        // The AI often outputs raw LaTeX like \Psi, \frac, \int, \dx etc.
        // We must double-escape any backslash that precedes an invalid JSON escape char.
        // Process character by character to catch every case.
        let fixed = '';
        for (let i = 0; i < sanitizedJson.length; i++) {
            const ch = sanitizedJson[i];
            if (ch === '\\' && i + 1 < sanitizedJson.length) {
                const next = sanitizedJson[i + 1];
                // Valid JSON escapes after backslash
                if ('"\\bfnrtu/'.includes(next)) {
                    fixed += ch; // keep single backslash, it's a valid JSON escape
                } else {
                    fixed += '\\\\'; // double it: this is a LaTeX command, needs escaping for JSON
                }
            } else {
                fixed += ch;
            }
        }
        sanitizedJson = fixed;
        
        // Clean up raw control characters that might break JSON.parse
        sanitizedJson = sanitizedJson.replace(/[\u0000-\u001F]+/g, ' ');

        try {
            const parsed: RevisionSheet = JSON.parse(sanitizedJson);
            return parsed;
        } catch (parseError: any) {
            console.error('JSON Parse Error original string:', jsonStr);
            throw new Error(`Parse Error: ${parseError.message}. AI Output excerpt: ${jsonStr.substring(0, 150)}...`);
        }

    } catch (error: any) {
        console.error('Revision Sheet AI Error:', error);
        throw new Error(error.message || 'Failed to generate revision sheet');
    }
};
