import { GoogleGenAI } from '@google/genai';
import * as FileSystem from 'expo-file-system/legacy';

const API_KEY = process.env.EXPO_PUBLIC_GEMINI_API_KEY;

const genAI = new GoogleGenAI({ apiKey: API_KEY || '' });

export interface QuizQuestion {
    question: string;
    options: string[];
    answer: number;
}

export interface StudyMaterial {
    explanation: string;
    summary: string[];
    quiz: QuizQuestion[];
}

export const generateStudyMaterial = async (imageUri: string): Promise<StudyMaterial> => {
    if (!API_KEY) {
        console.warn("Gemini API Key is missing");
        // Return mock data for demo if key is missing
        return MOCK_RESULT;
    }

    try {
        const base64 = await FileSystem.readAsStringAsync(imageUri, {
            encoding: 'base64',
        });

        const prompt = `
            Analyze this image of study notes, textbooks, or handwriting. 
            Extract and organize the core educational content into a structured JSON format.
            
            Return exactly this structure:
            {
                "explanation": "A comprehensive yet easy-to-understand explanation of the key concepts identified in the image (2-4 paragraphs). Use markdown for bolding terms.",
                "summary": [
                    "Key point 1",
                    "Key point 2",
                    "Key point 3"
                ],
                "quiz": [
                    {
                        "question": "A multiple choice question based on the content.",
                        "options": ["Option A", "Option B", "Option C", "Option D"],
                        "answer": 0 
                    }
                ]
            }
            
            Rules:
            - The "answer" must be the index (0-3) of the correct option in the "options" array.
            - Provide up to 20 quiz questions.
            - Provide 5-15 summary points.
            - If handwriting is illegible, make an educated guess or focus on legible parts.
        `;

        const result = await genAI.models.generateContent({
            model: "gemini-2.5-flash-lite",
            contents: [
                {
                    role: 'user',
                    parts: [
                        { text: prompt },
                        {
                            inlineData: {
                                data: base64,
                                mimeType: "image/jpeg"
                            }
                        }
                    ]
                }
            ],
            config: {
                responseMimeType: "application/json",
            }
        });

        const candidate = result.candidates?.[0];
        const text = candidate?.content?.parts?.[0]?.text;

        if (!text) {
            console.error('Gemini API empty response:', result);
            throw new Error('No content was generated by the Gemini model.');
        }

        // Robust JSON extraction
        let jsonStr = text;
        const jsonStart = text.indexOf('{');
        const jsonEnd = text.lastIndexOf('}');

        if (jsonStart !== -1 && jsonEnd !== -1) {
            jsonStr = text.substring(jsonStart, jsonEnd + 1);
        }

        const parsed: StudyMaterial = JSON.parse(jsonStr);

        // Basic validation
        if (!parsed.explanation || !Array.isArray(parsed.summary) || !Array.isArray(parsed.quiz)) {
            throw new Error('Invalid JSON structure returned by Gemini');
        }

        return parsed;

    } catch (error) {
        console.error('Gemini API Error:', error);
        throw error;
    }
};

const MOCK_RESULT: StudyMaterial = {
    explanation: "Photosynthesis is the process used by plants, algae and certain bacteria to harness energy from sunlight and turn it into chemical energy.",
    summary: [
        "Converts light energy to chemical energy.",
        "Occurs in chloroplasts.",
        "Produces glucose and oxygen."
    ],
    quiz: [
        {
            question: "Where does photosynthesis occur?",
            options: ["Mitochondria", "Chloroplasts", "Nucleus", "Ribosomes"],
            answer: 1
        },
        {
            question: "What is the primary output of photosynthesis?",
            options: ["Carbon Dioxide", "Water", "Glucose", "Nitrogen"],
            answer: 2
        },
        {
            question: "Which pigment absorbs light energy?",
            options: ["Hemoglobin", "Chlorophyll", "Melanin", "Carotene"],
            answer: 1
        }
    ]
};

export const sendChatMessage = async (history: { role: string; text: string }[], newMessage: string) => {
    if (!API_KEY) {
        return "This is a mock response because the API key is missing. Feel free to ask another question!";
    }

    try {
        // Map history to the format expected by the GoogleGenAI SDK
        // Note: genAI SDK v2 uses 'user' and 'model' as roles
        const contents = history.map(h => ({
            role: h.role === 'ai' ? 'model' : 'user',
            parts: [{ text: h.text }]
        }));

        contents.push({
            role: 'user',
            parts: [{ text: newMessage }]
        });

        const result = await genAI.models.generateContent({
            model: "gemini-2.5-flash-lite", // Using flash-lite for speed and cost
            contents: contents,
            config: {
                systemInstruction: "You are an expert AI tutor explaining study material. Be super helpful, concise, and encourage learning. Use markdown for formatting.",
            }
        });

        const text = result.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!text) throw new Error("No response from AI");
        return text;
    } catch (error) {
        console.error("Gemini Chat Error:", error);
        throw error;
    }
};
